specmesh/specmesh-build

parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java, parser/src/main/java/io/specmesh/apiparser/model/Message.java, parser/src/main/java/io/specmesh/apiparser/model/Tag.java, parser/src/test/java/io/specmesh/apiparser/AsyncApiParserTest.java, parser/src/test/java/io/specmesh/apiparser/AsyncApiSchemaParserTest.java, parser/src/test/resources/london_hammersmith_transport_public_passenger.avsc, parser/src/test/resources/simple_schema_demo-api.yaml, parser/src/test/resources/simple_schema_demo_user-signedup.avsc
Important semantic notes
- Publisher will need to publish schema to SR
- Subscriber will reference the schema name from the spec and load it from the required SR to codegen classes.
- Schema is not shipped outside of the data product, and only available to subscribers via the SR and should no be contained in subscriber apps
=> First part of Schema support

.github/workflows/release.yml
Releasing writes a tag back to the repo's main branch, (which then triggers the build), so the job needs write permission on the repo's content to be able to push the tag.
=> Enable releasing

.github/workflows/release.yml
By default, if a GitHub workflow pushes a tag it will NOT trigger any other workflows that would normally trigger if the tag was pushed manually.
To trigger workflows a PAT must be used.
(Which is a bit rubbish!)
=> Allow release workflow to trigger another workflow

.github/dependabot.yml, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
Refactor `KafkaAPISpecFunctionalTest` to use a cartesian test of:
- Topic: [public, protected, private]
- Producer domain: [ self (the domain associated with the spec), unrelated (an unrelated domain), limited (domain granted access to the protected topic) ]
- Consumer domain: [self, unrelated, limited]
This ensures all combinations are tested.
=> Switch to cartesian test to ensure all combos covered

build.gradle.kts, kafka-test/src/main/java/io/specmesh/kafka/KafkaEnvironment.java, kafka-test/src/main/java/io/specmesh/test/TestSpecLoader.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java, parser/src/test/java/io/specmesh/apiparser/TestSpecLoader.java
`org.junit.jupiter.api.extension.Extension` is a marker interface for Junit5 extensions. (Everything works without it, but IntelliJ highlights usage as possibly incorrect).
Snuck in a few other unrelated minors.
=> Bug: `KafkaEnvironment` should extend `org.junit.jupiter.api.extension.Extension`

.github/workflows/dependabot-auto-merge.yml
Dependabot is configured to raise PRs for updating dependencies in the project. But, managing the PRs is a PITA. So, let's automate it...
=> Add workflow to auto-merge dependabot PRs

cli/build.gradle.kts, cli/src/main/java/io/specmesh/cli/ProvisionCommand.java, cli/src/main/java/io/specmesh/cli/SpecConsumptionCommand.java, cli/src/main/java/io/specmesh/cli/SpecStorageCommand.java, cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java, cli/src/test/java/io/specmesh/cli/StorageConsumptionMetricsFunctionalTest.java, cli/src/test/java/simple/schema_demo/_public/user_checkout_value/UserCheckout.java, cli/src/test/java/simple/schema_demo/_public/user_signed_up_value/UserSignedUp.java, cli/src/test/resources/schema/simple.schema_demo._public.user_info.proto, cli/src/test/resources/simple_schema_demo-api.yaml, kafka/src/main/java/io/specmesh/kafka/admin/SimpleAdminClient.java, kafka/src/main/java/io/specmesh/kafka/admin/SmAdminClient.java, kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/SchemaWriters.java, kafka/src/test/java/io/specmesh/kafka/admin/SimpleAdminClientTest.java, kafka/src/test/resources/clientapi-functional-test-api.yaml, kafka/src/test/resources/schema/simple.schema_demo._public.user_info.proto
#84  - Introduce storage and consumption metrics on a per-spec basis. 
- break down consumption by group-id, including member-info and offset as well as total
- break down production to broker-storage bytes and total offset
the outputs can be used to build a chargeback model against
=> #84 - adding capability to track production and consumption

cli/src/main/java/io/specmesh/cli/Provision.java, cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java, kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/SchemaChangeSetCalculators.java, kafka/src/main/java/io/specmesh/kafka/provision/SchemaMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/SchemaReaders.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicChangeSetCalculators.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicProvisioner.java, kafka/src/test/java/io/specmesh/kafka/ExporterFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/ProvisionerUpdatingFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/SchemaProvisionerUpdateFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/admin/SimpleAdminClientTest.java, kafka/src/test/java/io/specmesh/kafka/provision/SchemaChangeSetCalculatorsTest.java, kafka/src/test/java/io/specmesh/kafka/provision/TopicMutatorsTest.java
#58 Topics: remove resources that aren't in the spec. provides a means of preventing resource drift and using the spec as the source of truth
note on 'Provision' command updated flags:
- use -dry or --dry-run to check action (inc cleaning)
- use -clean or --clean-unspecified to clean resources
=> enhancement - #58 topic cleanup non-spec topic - part 1

kafka/src/main/java/io/specmesh/kafka/provision/AclChangeSetCalculators.java, kafka/src/main/java/io/specmesh/kafka/provision/AclMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/AclProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/AclReaders.java, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/test/java/io/specmesh/kafka/AclProvisionerUpdateFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/TopicProvisionerUpdateFunctionalTest.java
Cleanup ACLs that aren't part of this spec. The adminClient ACL interface is terrible - you need to pull back all ACLs - there will be 3 for all private topics (prefixed), 3 for all public topic, and 3 for each/every protected topic. Where ACLs are excessive (i.e. too many topics - then avoid using 'protected' topic.
use Provisioner with -clean true -dry true flags.
-dry-run + -clean will display set of all resources to be cleaned
use Provisioner with -clean true -dry false flags to remove the reported set above
cherry picking not currently supported. could be a nice feature request
=> part 3 - ACLs for unspec cleanup #58

cli/Dockerfile, cli/build.gradle.kts
fixes: https://github.com/specmesh/specmesh-build/issues/213
* First change:
Have the Gradle build unpack the distribution tar archive. This means there is no need to install tar or to have the tar file in the Docker image.
Reduces image down to ~600MB
* Second change:
Change base image to smaller one:
Reduces image down to ~360MB
=> Reduce size of cli docker image by removing tar

cli/README.md, cli/build.gradle.kts, cli/include/bin/wrapper.sh, cli/resources/simple_schema_demo-api.yaml, cli/src/main/java/io/specmesh/cli/Export.java, cli/src/main/java/io/specmesh/cli/Flatten.java, cli/src/test/java/io/specmesh/cli/FlattenTest.java, cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java
See #221 - example command to flatten:
` % docker run --rm  -v "$(pwd)/resources:/app" ghcr.io/specmesh/specmesh-build-cli flatten --in-spec /app/simple_schema_demo-api.yaml --out-spec /app/testing.yaml`
Changes:
```yaml
channels:
_public.user_signed_up:
```
into
```yaml
channels:
simple.schema_demo._public.user_signed_up:
```
=> flattening structures for use by other AsyncApi spec tools

kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java, kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
Currently, running a JUnit5 test such as:
```java
class MyTest {
@RegisterExtension
private static final KafkaEnvironment KAFKA_ENV =
DockerKafkaEnvironment.builder()
.build();
@nested
class InnerTest {
// Blah...
}
}
```
Won't work, as `DKE.setUp` gets called twice by JUnit. Once for the outer and once for the inner. Go figure.
=> Allow nested tests

README.md, kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java, kafka/src/test/java/io/specmesh/kafka/provision/TopicMutatorsTest.java, parser/src/main/java/io/specmesh/apiparser/model/Operation.java, parser/src/test/java/io/specmesh/apiparser/AsyncApiSchemaParserTest.java, parser/src/test/resources/parser_simple_schema_demo-api.yaml
Currently, if a channel is defined with no `message` then the `operation.schemaInfo()` call throws an NPE.  `message` is not required, so a `null` `message should not cause an NPE.
=> Don't blow up if no message is defined

kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
There's no reason why the spec needs to be on the classpath - in fact I'd say it's more normal for it to be on the filesystem - so allow this as a first class citizen of the api
=> Allow users to load spec from the file system

README.md, cli/README.md, cli/src/main/java/io/specmesh/cli/Storage.java, cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java
Changed `storage` metric to `storage-bytes`, cos units matter!
=> Add units to `storage`

cli/src/main/java/io/specmesh/cli/Provision.java, cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java, cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java, kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java, kafka/src/main/java/io/specmesh/kafka/Clients.java, kafka/src/main/java/io/specmesh/kafka/provision/AclMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/AclProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/AclReaders.java, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/ProvisioningException.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicReaders.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaProvisioner.java, kafka/src/test/java/io/specmesh/kafka/ExporterFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/admin/SimpleAdminClientTest.java, kafka/src/test/java/io/specmesh/kafka/provision/AclProvisionerUpdateFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/provision/ProvisionerTest.java, kafka/src/test/java/io/specmesh/kafka/provision/TopicProvisionerTest.java, kafka/src/test/java/io/specmesh/kafka/provision/schema/SchemaChangeSetCalculatorsTest.java
BREAKING CHANGE: `Provision` and `Provisioner` types changes are not backwards compatible, depending on usage. Command line should not have changed.
Previous design didn't allow for new versions to accept new parameters to be provided. Using a builder factory makes the api more evolvable.
=> Evolvable `Provisioner` api

cli/src/main/java/io/specmesh/cli/Provision.java, kafka/src/main/java/io/specmesh/kafka/Clients.java, kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java, kafka/src/main/java/io/specmesh/kafka/provision/AclProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java, kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/provision/AclProvisionerUpdateFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/provision/ProvisionerTest.java
Some platforms do not allow the administrator to control / choose the name of the principle. Instead, it is a generated name.
For example, Confluent Cloud when using Service Accounts, uses the system generated account id as the principle name, e.g. `sa-l35n4kd`
Specmesh now supports tweaking the ACLs created to use the system generated principle name via:
1. the `Provisioner.builder().domainUserAlias("bob")` method.
2. the `--domain-user` or `-du` command line parameters to `Provision` command.
=> Support generated usernames

kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java
`DockerKafkaEnvironment.Builder.withSchemaRegistryEnv` calls were incorrectly being sent to the Kafka container, not the Schema registry container.
=> Fix sr env in `DockerKafkaEnvironment`

cli/resources/simple_schema_demo-api.yaml, kafka/src/main/java/io/specmesh/kafka/Exporter.java, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/test/java/io/specmesh/kafka/provision/ProvisionerTest.java, kafka/src/test/resources/bigdatalondon-api-with-grant-access-acls.yaml, kafka/src/test/resources/bigdatalondon-api.yaml, kafka/src/test/resources/customacl-bigdatalondon-api.yaml, parser/src/main/java/io/specmesh/apiparser/model/ApiSpec.java, parser/src/main/java/io/specmesh/apiparser/model/Bindings.java, parser/src/main/java/io/specmesh/apiparser/model/Channel.java, parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java, parser/src/main/java/io/specmesh/apiparser/model/Operation.java, parser/src/test/java/io/specmesh/apiparser/model/OperationTest.java, parser/src/test/resources/parser_simple_schema_demo-api.yaml, parser/src/test/resources/test-streetlights-simple-api.yaml
`operationId` is a required field of `Operation`, but the check for it is only done in the provision call. This means the parser can return a spec that is invalid = bad.
This change makes the parsing fail if the `operationId` is missing.
The change also applies the "don't allow your objects to get into an invalid state" best practice. Which removes the need for a `validate` method.
=> Spec's returned from parser should be valid.

kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaProvisioner.java, kafka/src/test/java/io/specmesh/kafka/provision/SchemaProvisionerReferenceTest.java, kafka/src/test/resources/schema-ref/com.example.single-spec-with-refs-api.yml
. Added test to load a spec with Currency and also Trade - currency is ref'd by Trade, the sort will ensure that '0' ref schemas register first. hard to test due to channel names being stored in a map
=>   #406 ensure schema references are ordered correctly

parser/src/main/java/io/specmesh/apiparser/model/ApiSpec.java, parser/src/test/java/io/specmesh/apiparser/model/ApiSpecTest.java
don't allow a spec to just have:
```
id: urn: 
```
It needs to define the domain id if things are to work correctly, e.g.
```
id: urn:my.domain.id
```
=> Require domain id

build.gradle.kts, kafka-test/build.gradle.kts, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaReaders.java, kafka/src/test/java/io/specmesh/kafka/provision/ProvisionerTest.java, kafka/src/test/java/io/specmesh/kafka/provision/SchemaProvisionerFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/provision/SchemaProvisionerReferenceTest.java, kafka/src/test/resources/provisioner-functional-test-api.yaml, kafka/src/test/resources/schema-ref/com.example.shared-api.yml, kafka/src/test/resources/schema-ref/com.example.trading-api.yml
There's already code to load a spec from the classpath, yet if that spec references schemas which as also available on the classpath, it fails.
This PR:
- introduces a `SchemaReaders.ClassPathSchemaReader` that loads schemas from the classpath
- introduces a `SchemaReaders.BaseLocalSchemaReader` and moves common functionality from `FileSystemSchemaReader` into it.
- introduces a `SchemaReaders.LocalSchemaReader` that tries to load from the classpath first and filesystem second.
- changes production usage of `FileSystemSchemaReader` to `LocalSchemaReader`
Additionally, this PR:
- sets the default schema path to an empty string, rather than an NPE being thrown if `schemaPath()` is not called.
- marks `:parser` and `:kafka` modules as part of the api of `:kafka-test` as they are part of the …
=> Allow loading schemas from the classpath

kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java, kafka-test/src/main/java/io/specmesh/kafka/KafkaEnvironment.java, kafka-test/src/main/java/io/specmesh/kafka/schema/SchemaRegistryContainer.java, kafka-test/src/test/java/io/specmesh/kafka/DockerKafkaEnvironmentTest.java
... and:
* added a public `start()` and `close()` method for when not using with JUnit.
* added simple test for `DockerKafkaEnvironment`
* removed a deprecated method.
* deprecated `SchemaRegistryContainer.withKafka` as its not used, not needed and the `KafkaContainer` parameter is deprecated in the next version of TestContainers.
* fix a few warnings.
=> Add tests to DockerKafkaEnvironment

cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java, kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java, kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java, kafka-test/src/test/resources/kafka_test-simple_schema_demo-api.yaml, kafka-test/src/test/resources/log4j2-test.xml, kafka/README.md, kafka/src/main/java/io/specmesh/kafka/Clients.java
Test and document a way to set up a KafkaStreams topology so that internal topics, i.e. changelog and repartition topics, abide by SpecMesh channel / topic naming standards.
=> Test & document Kafka streams internal topics

cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java, kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java, kafka/src/main/java/io/specmesh/kafka/Clients.java, kafka/src/test/java/io/specmesh/kafka/ClientsTest.java, kafka/src/test/java/io/specmesh/kafka/admin/SimpleAdminClientTest.java
Let's make `Clients` a bit more type-safe and user-friendly.
Have left all the existing legacy methods there, but deprecated.
See functional tests for examples of using the new flow / builder versions, which are more flexible and more easily extended in the future without breaking existing clients.
=> Improve `Clients`

cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java, kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java, kafka/src/main/java/io/specmesh/kafka/Clients.java, kafka/src/test/java/io/specmesh/kafka/ClientsTest.java
Updates the new `Clients` methods to _not_ set `use.latest.version` / `USE_LATEST_VERSION` to `true`.
We should _not_ be doing this by default, as it means producers use the latest registered schema, rather than the schema version they were compiled to run with.
With this setting on, rolling back a recent release would not mean the older version would use the older schema: it would continue to use the latest schema.
Some tests, i.e. those using reflection, have been updated to still set this to `true` as otherwise they won't work due to the fact that the generated isn't actually registered.
Also set `AVRO_REMOVE_JAVA_PROPS_CONFIG` / `avro.remove.java.properties` so that the additional fields avro has injected into the schema referenced by the generated classes are removed. Without this, …
=> Do not set `use.latest.version` to true in `Clients`

cli/src/test/java/io/specmesh/cli/ProvisionNestedFunctionalTest.java, kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecWithGrantAccessAclsTest.java, kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java
Fixes: #454
KafkaStreams apps use the `DELETE_RECORDS` operation on repartition topics to automatically delete records that have been processed. This required the `DELETE` permission on the topic to succeed.
We need to decide if we are happy given domain users the writes to delete their own topics.
Personally, I think giving `DELETE` topic permissions seems like a valid thing to do: after all, they are owned by the domain user, so why can't they delete them if they want?  They can always provision them again later.
Con: this does open the doorway to the state in Kafka being out of whack with the spec.
Pro: it empowers domain owners to clean down Kafka topics if they need republishing etc.
Likewise, this change gives domain owners the ability to delete their own consumer groups, should …
=> Allow records in private topics to be removed.

cli/src/test/java/io/specmesh/cli/ProvisionCommonSchemaFunctionalTest.java, cli/src/test/java/io/specmesh/cli/ProvisionNestedSchemaFunctionalTest.java, cli/src/test/java/io/specmesh/cli/util/CommonSchema.java, cli/src/test/resources/schema/other.domain.Common.avsc, cli/src/test/resources/schema/other.domain.CommonKey.avsc, cli/src/test/resources/schema/other.domain.CommonOther.avsc, cli/src/test/resources/schema/simple.schema_demo.SuperUserSignedUp.avsc, cli/src/test/resources/shared_schema_demo-api.yaml, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaChangeSetCalculators.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaOwnership.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaReaders.java, kafka/src/test/java/io/specmesh/kafka/provision/schema/SchemaMutatorsTest.java
fixes: #427
fixes: #452
SpecMesh already allows schema owned by other domains to be referenced by schema owned by the domain.  When encountered, such non-owned schema are ignored, i.e. to attempt is made to register them.  However, dependent schemas will fail to register if the non-owned schema is not already registered.
What was not supported till now, was a channel directly referencing a non-owned schema. What is called a 'topic schema' in the code. In this instance, the schema needs to be registered against the appropriate `${topic.name}-key` or `${topic.name}-value` subject, otherwise things won't work.
As the schema isn't owned by the domain, it can't just register the schema. Instead, it first ensures the schema is already registered under a subject name that matches its fully …
=> Support non-owned topic schema.

kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaMutators.java, kafka/src/main/java/io/specmesh/kafka/schema/RegisteredSchema.java, parser/src/main/java/io/specmesh/apiparser/model/Message.java, parser/src/main/java/io/specmesh/apiparser/model/SchemaInfo.java, parser/src/test/java/io/specmesh/apiparser/model/TagTest.java
e.g. I couldn't create a `Tag` instance in my test code as there was only a private no-args constructor...
=> Ensure the value types can be constructed in user code

kafka/src/main/java/io/specmesh/kafka/provision/schema/AvroReferenceFinder.java, kafka/src/test/java/io/specmesh/kafka/provision/schema/AvroReferenceFinderTest.java
Fixes: 516
There was an issue where nested schemas could cause failures if the same nested schema was referenced more than once. This change fixes this issue.
=> Fix the issue with nested schemas when referenced multiple times

README.md, cli/src/main/java/io/specmesh/cli/Provision.java, kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicMutators.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicProvisioner.java, kafka/src/main/java/io/specmesh/kafka/provision/TopicReaders.java, kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/TopicProvisionerUpdateFunctionalTest.java, kafka/src/test/java/io/specmesh/kafka/provision/ProvisionerTest.java, kafka/src/test/java/io/specmesh/kafka/provision/TopicProvisionerTest.java
Fixes: #464
Adds new `--partition-count-factor` command line argument and `Provisioner.partitionCountFactor()` method to allow a factor to be set (`0 < factor <= 1.0`) to reduce the number of partitions that will be created for new topics.
This can be useful to reduce partition counts in smaller non-prod environments, without changing the spec.
An alternative approach, worth considering, is to put the counts into the spec:
```yaml
channels:
_private.instrument:
bindings:
kafka:
envs:
- loadtest:
patitions: 10
- prod:
patitions: 10
partitions: 3
```
Which may be a better solution, but requires more work
=> Add ability to factor down partition counts

kafka/src/main/java/io/specmesh/kafka/provision/schema/AvroReferenceFinder.java, kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaReaders.java, kafka/src/test/java/io/specmesh/kafka/provision/schema/AvroReferenceFinderTest.java
Improves the exceptions thrown when loading and parsing Avro referenced types from external files.  Message now includes the chain of schema files that led to the issue, e.g. fileA -> fileB -> fileWithIssues
=> Improved schema reference related error messages
