- parser/src/main/java/io/specmesh/apiparser/model/ApiSpec.java
- parser/src/main/java/io/specmesh/apiparser/model/Channel.java
- parser/src/main/java/io/specmesh/apiparser/model/Message.java
- parser/src/main/java/io/specmesh/apiparser/model/Operation.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiParserTest.java
> #3 completing support of canonical channel names

- parser/src/main/java/io/specmesh/apiparser/model/ApiSpec.java
- parser/src/main/java/io/specmesh/apiparser/model/Channel.java
- parser/src/main/java/io/specmesh/apiparser/model/Message.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiParserTest.java
- parser/src/test/resources/test-streetlights-simple-api.yaml
As per #6  - needed to move the bindings. See here:  https://github.com/asyncapi/bindings/tree/master/kafka
> #6 refined to accurately follow the spec

- build.gradle.kts
- kafka/build.gradle.kts
- kafka/src/test/java/io/specmesh/kafka/ACLTest.java
- settings.gradle.kts
not finished but sion needs it
> pulling in for sion to leverage

- build.gradle.kts
- kafka/build.gradle.kts
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/test/java/io/specmesh/kafka/ACLTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
- kafka/src/test/java/io/specmesh/kafka/SASLPlainPrincipleTest.java
- kafka/src/test/resources/bigdatalondon-api.yaml
- parser/build.gradle.kts
- parser/src/main/java/io/specmesh/apiparser/model/ApiSpec.java
- parser/src/main/java/io/specmesh/apiparser/model/Bindings.java
- parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java
- parser/src/main/java/io/specmesh/apiparser/model/Message.java
- parser/src/main/java/io/specmesh/apiparser/model/Operation.java
- parser/src/main/java/io/specmesh/apiparser/model/Tag.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiParserTest.java
- parser/src/test/resources/test-streetlights-simple-api.yaml
Incremental fixes,
- fixed lombok annoations
- added KafkaAPIParser
> ACL support - part 2 of 3

- build.gradle.kts
- kafka/build.gradle.kts
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/main/java/io/specmesh/kafka/schema/JsonSchemas.java
- kafka/src/main/java/io/specmesh/kafka/schema/RegisteredSchema.java
- kafka/src/main/java/io/specmesh/kafka/schema/SrSchemaManager.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
- kafka/src/test/java/io/specmesh/kafka/schema/SrSchemaManagerTest.java
- kafka/src/test/resources/bigdatalondon-api.yaml
- kafka/src/test/resources/schema/london_hammersmith_transport_public_passenger.avsc
- kafka/src/test/resources/schema/simple_schema_demo_user-signedup.avsc
- kafka/src/test/resources/schema/test_model_v2_schema.yml
- kafka/src/test/resources/schema/test_party_schema.yml
- kafka/src/test/resources/schema/test_party_v2_schema.yml
- kafka/src/test/resources/simple_schema_demo-api.yaml
- parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java
- parser/src/main/java/io/specmesh/apiparser/model/Operation.java
- parser/src/main/java/io/specmesh/apiparser/model/SchemaInfo.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiSchemaParserTest.java
- basic schema registry client tests
-  message level kafka binding with schema info
> Schema support - second pass 

- build.gradle.kts
- kafka/build.gradle.kts
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISchemasFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
- kafka/src/test/java/io/specmesh/kafka/SASLPlainPrincipleTest.java
- kafka/src/test/java/io/specmesh/kafka/schema/SchemaRegistryContainer.java
- kafka/src/test/java/io/specmesh/kafka/schema/SrSchemaManagerTest.java
- kafka/src/test/java/simple/schema_demo/_public/user_signed_up_value/UserSignedUp.java
- kafka/src/test/resources/schema/simple.schema_demo._public.user_signed_up.avsc
- kafka/src/test/resources/simple_schema_demo-api.yaml
Demo avro serialization tests for #3
> AVRO with demo code and SpecMesh integration

- kafka/build.gradle.kts
- kafka/src/main/java/io/specmesh/kafka/schema/JsonSchemas.java
- kafka/src/test/java/io/specmesh/kafka/schema/SrSchemaManagerTest.java
- kafka/src/test/java/simple/schema_demo/_public/user_checkout_value/UserCheckout.java
- kafka/src/test/resources/schema/simple.schema_demo._public.user_checkout.yml
- kafka/src/test/resources/simple_schema_demo-api.yaml
- parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiSchemaParserTest.java
- parser/src/test/resources/simple_schema_demo-api.yaml
> JSON Schema demo

- kafka/src/main/java/io/specmesh/kafka/Provisioner.java
- kafka/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/resources/apispec-functional-test-app.yaml
push provisioner to more tests
> push provisioner to more tests

- build.gradle.kts
- kafka/src/main/java/io/specmesh/kafka/Clients.java
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/main/java/io/specmesh/kafka/Provisioner.java
- kafka/src/main/java/io/specmesh/kafka/schema/JsonSchemas.java
- kafka/src/main/java/io/specmesh/kafka/schema/RegisteredSchema.java
- kafka/src/main/java/io/specmesh/kafka/schema/SchemaRegistryContainer.java
- kafka/src/main/java/io/specmesh/kafka/schema/SrSchemaManager.java
- kafka/src/test/java/io/specmesh/kafka/AbstractContainerTest.java
- kafka/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
- kafka/src/test/java/io/specmesh/kafka/SASLPlainPrincipleTest.java
- kafka/src/test/java/io/specmesh/kafka/schema/SimpleSchemaDemoPublicUserInfo.java
- kafka/src/test/java/io/specmesh/kafka/schema/SimpleSchemaDemoPublicUserInfoEnriched.java
- kafka/src/test/java/io/specmesh/kafka/schema/SrSchemaManagerTest.java
- kafka/src/test/java/simple/schema_demo/_public/user_checkout_value/UserCheckout.java
- kafka/src/test/java/simple/schema_demo/_public/user_signed_up_value/UserSignedUp.java
- parser/src/main/java/io/specmesh/apiparser/AsyncApiParser.java
- parser/src/main/java/io/specmesh/apiparser/model/ApiSpec.java
- parser/src/main/java/io/specmesh/apiparser/model/Bindings.java
- parser/src/main/java/io/specmesh/apiparser/model/Channel.java
- parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java
- parser/src/main/java/io/specmesh/apiparser/model/Message.java
- parser/src/main/java/io/specmesh/apiparser/model/Operation.java
- parser/src/main/java/io/specmesh/apiparser/model/SchemaInfo.java
- parser/src/main/java/io/specmesh/apiparser/model/Tag.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiParserTest.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiSchemaParserTest.java
> reformatting with spotless

- build.gradle.kts
- kafka/build.gradle.kts
- kafka/src/test/java/io/specmesh/kafka/schema/SchemaRegistryContainer.java
- parser/build.gradle.kts
Tidy up dependencies a bit, fix a few issues and prep for publishing jars
> Prep for releasing jars

- kafka-test/src/test/resources/simple_schema_demo-api.yaml
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/main/java/io/specmesh/kafka/schema/SrSchemaManager.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/resources/apispec-functional-test-app.yaml
- kafka/src/test/resources/bigdatalondon-api.yaml
- parser/src/main/java/io/specmesh/apiparser/model/KafkaBinding.java
- parser/src/main/java/io/specmesh/apiparser/model/Operation.java
- parser/src/main/java/io/specmesh/apiparser/model/SchemaInfo.java
- parser/src/test/resources/simple_schema_demo-api.yaml
It isnt needed. Also fixing javadoc comments
> Removing schemaIdPayloadLocation param

- .github/workflows/build.yml
- README.md
... and configure release workflow to auto release to Maven
> Update README with Maven publishing

- kafka-test/src/main/java/io/specmesh/kafka/AbstractContainerTest.java
- kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/src/main/java/io/specmesh/kafka/Clients.java
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/main/java/io/specmesh/kafka/Provisioner.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
- kafka/src/test/resources/apispec-functional-test-app.yaml
- kafka/src/test/resources/bigdatalondon-api.yaml
Notes:
- clients demo includes security
- provisioner bulk operation added (topics, schemas, acls)
- relative topics use of underscore prefixing '_public' applied everywhere/properly
- tidy up tests
@big-andy-coates  - pls review!
> Added security to clients demo and Provisioner bulk operation method added

- kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
- kafka/src/test/java/io/specmesh/kafka/SASLPlainPrincipleTest.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiParserTest.java
- parser/src/test/java/io/specmesh/apiparser/AsyncApiSchemaParserTest.java
> A bit of refactoring

- kafka/README.md
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
fixes: https://github.com/specmesh/specmesh-build/issues/61
> Allow domain services to create arbitrary private topics.

- kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/README.md
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecTest.java
...and also fix `IDEMPOTENT_WRITE` ACL for < v3.0 clusters that still need this.
fixes: https://github.com/specmesh/specmesh-build/issues/62
> Support transactional producers

- .github/dependabot.yml
- build.gradle.kts
... and limit the scope of confluent repo to only confluent components.
... and (unrelated) fix dependabot.yml (I thought `0` meant unlimited, turns out it means disable!)
> Remove unnecessary repositories

- .github/workflows/release.yml
Capture the current version once the release has been triggered and add to the job summary.
> Enhance the release workflow to document version

- cli/src/main/java/io/specmesh/cli/KafkaProvisionCommand.java
- cli/src/test/java/io/specmesh/cli/CliFunctionalTest.java
- kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/src/main/java/io/specmesh/kafka/ProvisionStatus.java
- kafka/src/main/java/io/specmesh/kafka/Provisioner.java
- kafka/src/test/java/io/specmesh/kafka/ExporterFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/ProvisionerFunctionalTest.java
- kafka/src/test/resources/provisioner-functional-test-api.yaml
subtask part of #86 - where the spec should be validated against the current env . This is the first pass. later will include cover missinmg functionality i.e. compatible topic config changes, schema validation etc
> Adding validator to check the spec

- build.gradle.kts
- kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java
Fixes: https://github.com/specmesh/specmesh-build/issues/89
> Switch to Gradle toolchain to set Java version 11.

- kafka/src/main/java/io/specmesh/kafka/Exporter.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclWriters.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaWriters.java
- kafka/src/main/java/io/specmesh/kafka/provision/TopicReaders.java
- kafka/src/main/java/io/specmesh/kafka/provision/TopicWriters.java
bring exporter up to date with Readers
> bring exporter up to date with Readers

- kafka/src/main/java/io/specmesh/kafka/provision/SchemaChangeSetCalculators.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaReaders.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaWriters.java
- kafka/src/test/java/io/specmesh/kafka/ProvisionerUpdatingFunctionalTest.java
- kafka/src/test/resources/provisioner-update-functional-test-api.yaml
- kafka/src/test/resources/schema/simple.provision_demo._public.user_signed_up-v2.avsc
allow schemas to be updated and compatibility checked. The output of compatibility checking is captured during dryRun and available via the cli
> support for schema updates and compatibility checking

- kafka/src/main/java/io/specmesh/kafka/provision/SchemaChangeSetCalculators.java
- kafka/src/test/java/io/specmesh/kafka/provision/SchemaChangeSetCalculatorsTest.java
- kafka/src/test/resources/schema/simple.provision_demo._public.user_signed_up-v3-bad.avsc
added compatibility test on changeset stage
> report schema breaks properly

- kafka/src/main/java/io/specmesh/kafka/provision/AclChangeSetCalculators.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclReaders.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclWriters.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaChangeSetCalculators.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaWriters.java
- kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/ProvisionerUpdatingFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/provision/SchemaChangeSetCalculatorsTest.java
- kafka/src/test/resources/provisioner-functional-test-api.yaml
- kafka/src/test/resources/provisioner-update-functional-test-api.yaml
- parser/src/main/java/io/specmesh/apiparser/model/Operation.java
Additive ACLs with spec updates - part of #94
> update acls deltas as part of #94

- build.gradle.kts
- cli/Dockerfile
- cli/README.md
- cli/build.gradle.kts
- cli/include/bin/run.sh
- cli/include/bin/wrapper.sh
- cli/include/log4j/log4j2.xml
- cli/resources/schema/simple.schema_demo._public.user_checkout.yml
- cli/resources/schema/simple.schema_demo._public.user_info.proto
- cli/resources/schema/simple.schema_demo._public.user_signed_up.avsc
- cli/resources/simple_schema_demo-api.yaml
- cli/resources/simple_spec_demo-api.yaml
- cli/src/main/java/io/specmesh/cli/Consumption.java
- cli/src/main/java/io/specmesh/cli/Provision.java
- cli/src/main/java/io/specmesh/cli/Storage.java
- cli/src/main/java/io/specmesh/cli/Utils.java
- config/spotbugs/suppressions.xml
- kafka/src/main/java/io/specmesh/kafka/provision/AclProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclReaders.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclWriters.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaReaders.java
support docker cli command execution. 
part 2 -  add testContainers of source built images
part 3 - implement the export command
> #81 - dockerise CLi commands

- cli/src/main/java/io/specmesh/cli/Export.java
> docker-cli part 2 #84

- README.md
- getgoingguides.md
- what-why-who.md
updated main readme and some child pages seed getting started guides
Part of  #129
> first pass at doc tasks

- README.md
- cli/README.md
- cli/include/bin/wrapper.sh
- cli/src/main/java/io/specmesh/cli/Storage.java
- kafka/src/main/java/io/specmesh/kafka/admin/SimpleAdminClient.java
> cli doc stuff

- cli/README.md
> tidyup cli doc

- cli/README.md
- cli/src/main/java/io/specmesh/cli/Consumption.java
- cli/src/main/java/io/specmesh/cli/Export.java
- cli/src/main/java/io/specmesh/cli/Provision.java
- cli/src/main/java/io/specmesh/cli/Storage.java
- cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java
> added system properties

- kafka/src/test/java/io/specmesh/kafka/KafkaAPISpecFunctionalTest.java
> fixing main build

- .github/workflows/build.yml
- cli/build.gradle.kts
> docker stuff

- kafka/README.md
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/test/java/io/specmesh/kafka/CustomAclKafkaAPISpecTest.java
- kafka/src/test/resources/customacl-bigdatalondon-api.yaml
> support customer acl keyword conventions

- kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaChangeSetCalculators.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaMutators.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaReaders.java
- kafka/src/test/java/io/specmesh/kafka/ProvisionerFreshStartFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/ProvisionerUpdatingFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/SchemaProvisionerUpdateFunctionalTest.java
- kafka/src/test/java/io/specmesh/kafka/provision/SchemaChangeSetCalculatorsTest.java
Unspec cleanup 58 p2 schemas
Part 2 - also see part 1 (topic resource cleanup)
> enhancement - #58 schema cleanup of non-spec - part 2

- README.md
- cli/README.md
- cli/include/bin/wrapper.sh
- cli/provision.properties
- cli/resources/provision.properties
- cli/src/main/java/io/specmesh/cli/Provision.java
- cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java
- kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/README.md
- kafka/src/main/java/io/specmesh/kafka/Clients.java
- kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java
- kafka/src/test/java/io/specmesh/kafka/admin/SimpleAdminClientTest.java
#198  - support feature flags and also `provision.properties`
> #198 - support flags and default properties files

- cli/README.md
- cli/src/main/java/io/specmesh/cli/Provision.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java
Relates to #218  where pico messes up boolean logic
> fixing default boolean operations with picocli

- cli/src/main/java/io/specmesh/cli/Provision.java
> fix borked flags

- cli/src/main/java/io/specmesh/cli/Consumption.java
- cli/src/main/java/io/specmesh/cli/Export.java
- cli/src/main/java/io/specmesh/cli/Flatten.java
- cli/src/main/java/io/specmesh/cli/Provision.java
- cli/src/main/java/io/specmesh/cli/Storage.java
- cli/src/test/java/io/specmesh/cli/FlattenTest.java
- cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java
- cli/src/test/java/io/specmesh/cli/StorageConsumptionFunctionalTest.java
> exposing cli as lombock builder for api use

- cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java
- cli/src/test/resources/simple_schema_demo-api.yaml
- cli/src/test/resources/simple_spec_demo-api.yaml
- kafka/src/main/java/io/specmesh/kafka/Clients.java
> improved client connectivity checks

- cli/src/main/java/io/specmesh/cli/Provision.java
- kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java
> Bugfix of provision command

- cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java
- kafka-test/src/test/java/io/specmesh/kafka/ClientsFunctionalDemoTest.java
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclMutators.java
- kafka/src/main/java/io/specmesh/kafka/provision/AclProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/ExceptionWrapper.java
- kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/SchemaProvisioner.java
- kafka/src/main/java/io/specmesh/kafka/provision/TopicProvisioner.java
@t0ffel  - this will sort the exception swallowing
> prevent exception stacks being swallowed

- build.gradle.kts
- cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java
- kafka/build.gradle.kts
- kafka/src/main/java/io/specmesh/kafka/KafkaApiSpec.java
> new packages and exception check

- kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java
- kafka-test/src/main/java/io/specmesh/kafka/schema/SchemaRegistryContainer.java
- kafka/src/test/java/io/specmesh/kafka/provision/SchemaChangeSetCalculatorsTest.java
> push to cflt 753

- kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaReaders.java
- kafka/src/test/resources/schema-ref/schema/com.example.trading.Trade.avsc
> support schema comments

- CONTRIBUTING.md
- README.md
> Fix errors in README

- cli/README.md
- kafka/README.md
docs for https://github.com/specmesh/specmesh-build/pull/341
> Add docs for new domain user setting

- cli/src/main/java/io/specmesh/cli/Provision.java
- cli/src/test/java/io/specmesh/cli/ProvisionFunctionalTest.java
- kafka/src/main/java/io/specmesh/kafka/provision/Provisioner.java
Get rid of weird status caching.
> API Clean up

- kafka-test/src/main/java/io/specmesh/kafka/DockerKafkaEnvironment.java
Add test network support so that container broker and schema registry can be accessed in unit tests e.g.
````
appStack =
new GenericContainer<>(
DockerImageName.parse("testing/datamesh-cdc-processor:1.0.0.0"))
.withEnv("KAFKA_BROKER", KAFKA_ENV.testNetworkKafkaBootstrapServers())
.withEnv("SCHEMA_REG_ENDPOINT", KAFKA_ENV.testNetworkSchemeRegistryServer())
````
> Add container network support

- build.gradle.kts
fixes: 526
AS per https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuring-your-plugin
> Fix publishing to Central

- cli/Dockerfile
- cli/src/test/java/io/specmesh/cli/DockerImageTest.java
> Update cli docker jre version 11 -> 17
